language: swift
osx_image: xcode11.3.1


script:
- xcodebuild test -project TravisSampleProject.xcodeproj -scheme TravisSampleProject -destination "platform=iOS Simulator,name=iPhone 11" -sdk iphonesimulator11.0
